siteTitle="Microgate"
baseColor = "rgb(128, 222, 234)"
linkPrefix = "/microgate"
docPages = [
  "/docs/",
  "/docs/getting-started/",
  "/docs/how-to-run/",
  "/docs/the-next-step/",
  "/docs/conclusion/",
]
